#RNA velocity
library(velocyto.R)
library(SeuratWrappers)
ldat <- ReadVelocity(file = "B6.loom")#B6.loom was generated by 12.RNA velocity.sh
bm <- as.Seurat(x = ldat)
bm[["percent.mt"]] <- PercentageFeatureSet(bm, pattern = "^mt-")	
bm[["percent.rb"]] <- PercentageFeatureSet(bm, pattern = "^Rp[sl]")
bm <- SCTransform(object = bm, assay = "spliced",vars.to.regress = c("nCount_spliced","percent.mt","percent.rb"),variable.features.n = 3000)
bm <- RunPCA(object = bm, verbose = FALSE)
bm <- FindNeighbors(object = bm, dims = 1:30)
bm <- FindClusters(object = bm,resolution=0.3)
bm <- RunUMAP(object = bm, dims = 1:30)
bm <- RunVelocity(object = bm)
ident.colors <- (scales::hue_pal())(n = length(x = levels(x = bm)))
names(x = ident.colors) <- levels(x = bm)
cell.colors <- ident.colors[Idents(object = bm)]
names(x = cell.colors) <- colnames(x = bm)

sc_setIdents<-function(objOUT,objIN,cluster)
{
	cells.use <- WhichCells(object = objIN,idents=c(cluster))
	objOUT <- SetIdent(object = objOUT, cells = cells.use, value = cluster)
}
#Set cell type
cells.use <- WhichCells(object = asthma_neu)
bm <- SetIdent(object = bm, cells = cells.use, value = 'Neu')
bm <- RunUMAP(object = bm, dims = 1:22)
bm_neu<-subset(bm,idents=c("Neu"))
bm_neu<-sc_setIdents(bm_neu,asthma_neu,0)
bm_neu<-sc_setIdents(bm_neu,asthma_neu,1)
bm_neu<-sc_setIdents(bm_neu,asthma_neu,2)
bm_neu<-sc_setIdents(bm_neu,asthma_neu,3)
#Fig4A
p1<-DimPlot(bm_neu)
#Fig4B
tiff(filename=paste0(results_path,"/Fig4B.tiff"),width=3.2,height=3.2)
show.velocity.on.embedding.cor(emb = Embeddings(object = bm_neu, reduction = "umap"), vel = Tool(object = bm_neu, slot = "RunVelocity"), 
	n = 100, scale = "log", cell.colors = ac(x = cell.colors, alpha = 0.5), 
    cex = 0.5, arrow.scale = 4, show.grid.flow = TRUE, min.grid.cell.mass = 0.2,min.arrow.size = 0.02, grid.n = 15, arrow.lwd = 1, do.par = FALSE, cell.border.alpha = 0.1)
dev.off()

my_gseaGO<-function(markers,group){
	EntrezID<-bitr(unique(markers$gene),fromType='SYMBOL',toType='ENTREZID',OrgDb=org.Mm.eg.db)
	markers<-merge(x=markers,y=EntrezID,by.x="gene",by.y="SYMBOL")
	geneList<-as.numeric(as.character(markers[markers$cluster==group,"avg_logFC"]))
	names(geneList) = as.character(markers[markers$cluster==group,"ENTREZID"])
	geneList= sort(geneList, decreasing = TRUE)
	gseaGO<- gseGO(geneList =geneList, 'org.Mm.eg.db', ont="BP", nPerm = 10000, minGSSize = 10, pvalueCutoff=1)
}

gseGO_neu1<-my_gseaGO(asthma_neu.marker,group = "1")
#Fig4C
bm_neu <- AddModuleScore(bm_neu, features = list(cc=g_BM),  ctrl = 100,name = "BM score")
FeaturePlot(bm_neu,features = c("BM.score1"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
#Fig4D
g_neumigration<-bitr(gseGO_neu1@geneSets["GO:1990266"][[1]],fromType='ENTREZID',toType='SYMBOL',OrgDb=org.Mm.eg.db)
tmp<-intersect(g_neumigration$SYMBOL,rownames(asthma_neu))
bm_neu <- AddModuleScore(bm_neu, features = list(cc=tmp),  ctrl = 100,name = "neutrophil.migration")
FeaturePlot(bm_neu,features = c("neutrophil.migration1"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
#Fig4E
g_cellcycle<-bitr(gseGO_neu1@geneSets["GO:0007049"][[1]],fromType='ENTREZID',toType='SYMBOL',OrgDb=org.Mm.eg.db)
tmp<-intersect(g_cellcycle$SYMBOL,rownames(bm_neu))
bm_neu <- AddModuleScore(bm_neu, features = list(cc=tmp),  ctrl = 100,name = "cell proliferation")
FeaturePlot(bm_neu,features = c("cell.proliferation1"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
#Fig4F
g_ifng<-bitr(gseGO_neu1@geneSets["GO:0034341"][[1]],fromType='ENTREZID',toType='SYMBOL',OrgDb=org.Mm.eg.db)
tmp1<-intersect(g_ifng$SYMBOL,rownames(bm_neu))
bm_neu <- AddModuleScore(bm_neu, features = list(cc=tmp1),  ctrl = 100,name = "response to IFN-gamma")
FeaturePlot(bm_neu,features = c("response.to.IFN.gamma1"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
#Fig4G
#sc_subpHeatmap was defined in “10.neutrophil subclustring.R”
sc_subpHeatmap(asthma_neu,"Fig4G.tiff",
c("Spi1","Cebpd","Bcl6","Sp1","Atf1","Atf3","Rel","Atf4","Jun","Cebpb","Xbp1","Nr4a1","Bhlhe40","Egr1","Mef2a","Nfe2l2",
"Rbpj","Runx1","Sp2","Klf6","Fli1","Irf1","Irf7","Irf9","Irf2","Stat1","Klf15","E2f3","Rreb1"))
#Fig4H
FeaturePlot(bm_neu,features = c("Spi1","Cebpd"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
#Fig4I
FeaturePlot(bm_neu,features = c("Egr1","Bhlhe40"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)


#show enriched interleukin and chemokines related pathways
tmp<-gseGO_neu1
tmp@result<-tmp@result[tmp@result$Description %in% grep("interleukin",tmp@result$Description,value = T,ignore.case = T) 
|tmp@result$Description %in% grep("chemo",tmp@result$Description,value = T,ignore.case = T),]
#Fig4J
heatplot(tmp,showCategory = 15,foldChange =neu1_geneList)
#Fig4K
FeaturePlot(bm_neu,features = c("Jak2","Il10rb"),min.cutoff = "q5",max.cutoff = "q95",sort.cell = T)
